export const TOOLS = [
  {
    id: "blog-post",
    name: "Blog Post",
    icon: "📝",
    color: "#ff6b35",
    category: "Writing",
    description: "Long-form articles with SEO-optimized structure",
    fields: [
      { key: "topic", label: "Topic", type: "text", placeholder: "e.g. The future of remote work in 2025" },
      { key: "tone", label: "Tone", type: "select", options: ["Professional", "Conversational", "Humorous", "Authoritative", "Inspirational"] },
      { key: "wordCount", label: "Word Count", type: "select", options: ["500 words", "800 words", "1200 words", "2000 words"] },
      { key: "audience", label: "Target Audience", type: "text", placeholder: "e.g. Marketing professionals" },
    ],
    systemPrompt: (fields) => `You are an expert content writer. Write a compelling blog post about "${fields.topic}" in a ${fields.tone?.toLowerCase() || "professional"} tone, approximately ${fields.wordCount || "800 words"}. Target audience: ${fields.audience || "general readers"}. Include an engaging introduction, well-structured body with subheadings, and a strong conclusion. Format with markdown.`,
  },
  {
    id: "social-media",
    name: "Social Caption",
    icon: "📱",
    color: "#e879f9",
    category: "Social",
    description: "Scroll-stopping captions for any platform",
    fields: [
      { key: "platform", label: "Platform", type: "select", options: ["Instagram", "Twitter/X", "LinkedIn", "TikTok", "Facebook"] },
      { key: "topic", label: "What's it about?", type: "text", placeholder: "e.g. New product launch for eco-friendly water bottle" },
      { key: "cta", label: "Call to Action", type: "text", placeholder: "e.g. Shop now, Learn more, Comment below" },
      { key: "tone", label: "Vibe", type: "select", options: ["Exciting", "Professional", "Funny", "Inspirational", "Casual"] },
    ],
    systemPrompt: (fields) => `You are a social media expert. Create 3 variations of ${fields.platform || "Instagram"} captions about: "${fields.topic}". Vibe: ${fields.tone || "Exciting"}. CTA: ${fields.cta || "Engage with audience"}. Include relevant hashtags. Make them attention-grabbing and platform-native.`,
  },
  {
    id: "email-copy",
    name: "Email Copy",
    icon: "✉️",
    color: "#38bdf8",
    category: "Marketing",
    description: "High-converting email campaigns and sequences",
    fields: [
      { key: "type", label: "Email Type", type: "select", options: ["Welcome Email", "Sales Email", "Newsletter", "Cold Outreach", "Re-engagement", "Announcement"] },
      { key: "product", label: "Product/Service", type: "text", placeholder: "e.g. SaaS project management tool" },
      { key: "goal", label: "Primary Goal", type: "text", placeholder: "e.g. Get users to upgrade to Pro" },
      { key: "tone", label: "Tone", type: "select", options: ["Professional", "Friendly", "Urgent", "Storytelling"] },
    ],
    systemPrompt: (fields) => `You are an email marketing expert. Write a compelling ${fields.type || "sales email"} for: "${fields.product}". Goal: ${fields.goal}. Tone: ${fields.tone || "Professional"}. Include subject line, preview text, body with clear structure, and strong CTA. Optimize for opens and clicks.`,
  },
  {
    id: "ad-copy",
    name: "Ad Copy",
    icon: "🎯",
    color: "#fb923c",
    category: "Marketing",
    description: "Paid ads that convert — Google, Meta, LinkedIn",
    fields: [
      { key: "platform", label: "Ad Platform", type: "select", options: ["Google Ads", "Facebook/Instagram", "LinkedIn", "Twitter/X", "YouTube"] },
      { key: "product", label: "Product/Service", type: "text", placeholder: "e.g. Online coding bootcamp" },
      { key: "usp", label: "Unique Selling Point", type: "text", placeholder: "e.g. Land a job in 6 months or money back" },
      { key: "audience", label: "Target Audience", type: "text", placeholder: "e.g. Career changers aged 25-40" },
    ],
    systemPrompt: (fields) => `You are an expert direct response copywriter. Create compelling ${fields.platform || "Facebook"} ad copy for: "${fields.product}". USP: ${fields.usp}. Audience: ${fields.audience}. Generate: headline variations, primary text, description. Focus on benefits, urgency, and clear CTA. Follow platform best practices.`,
  },
  {
    id: "seo-meta",
    name: "SEO Meta Tags",
    icon: "🔍",
    color: "#34d399",
    category: "SEO",
    description: "Title tags, meta descriptions that rank & click",
    fields: [
      { key: "page", label: "Page/Content Topic", type: "text", placeholder: "e.g. Best CRM software for small businesses" },
      { key: "keywords", label: "Target Keywords", type: "text", placeholder: "e.g. CRM software, small business CRM" },
      { key: "brand", label: "Brand Name", type: "text", placeholder: "e.g. HubSpot" },
    ],
    systemPrompt: (fields) => `You are an SEO expert. Generate optimized meta tags for: "${fields.page}". Target keywords: ${fields.keywords}. Brand: ${fields.brand || "the website"}. Create: 3 title tag variations (under 60 chars), 3 meta description variations (under 160 chars), OG title, OG description. Focus on click-through rate and keyword placement.`,
  },
  {
    id: "product-desc",
    name: "Product Description",
    icon: "🛍️",
    color: "#f472b6",
    category: "eCommerce",
    description: "Compelling descriptions that drive purchases",
    fields: [
      { key: "product", label: "Product Name", type: "text", placeholder: "e.g. Bamboo Ergonomic Office Chair" },
      { key: "features", label: "Key Features", type: "textarea", placeholder: "e.g. Lumbar support, height adjustable, eco-friendly materials" },
      { key: "audience", label: "Target Buyer", type: "text", placeholder: "e.g. Remote workers with back pain" },
      { key: "tone", label: "Brand Voice", type: "select", options: ["Luxury", "Friendly", "Technical", "Minimalist", "Playful"] },
    ],
    systemPrompt: (fields) => `You are an eCommerce copywriter. Write a compelling product description for: "${fields.product}". Features: ${fields.features}. Target buyer: ${fields.audience}. Brand voice: ${fields.tone || "Friendly"}. Include: hook, benefit-driven body, feature list, SEO-friendly language. Make it persuasive and conversion-optimized.`,
  },
  {
    id: "youtube-script",
    name: "YouTube Script",
    icon: "🎬",
    color: "#f87171",
    category: "Video",
    description: "Engaging scripts with hooks that retain viewers",
    fields: [
      { key: "topic", label: "Video Topic", type: "text", placeholder: "e.g. How to build a habit in 21 days" },
      { key: "duration", label: "Video Length", type: "select", options: ["2-3 minutes", "5-7 minutes", "10-12 minutes", "15+ minutes"] },
      { key: "style", label: "Style", type: "select", options: ["Educational", "Storytelling", "Tutorial", "Vlog", "Motivational"] },
      { key: "channel", label: "Channel Niche", type: "text", placeholder: "e.g. Productivity & self-improvement" },
    ],
    systemPrompt: (fields) => `You are a YouTube script writer. Write a ${fields.duration || "5-7 minute"} ${fields.style || "Educational"} script about: "${fields.topic}". Channel niche: ${fields.channel || "general"}. Structure: pattern interrupt hook (first 15 seconds), intro with value promise, main content sections, engagement prompts (like/subscribe), outro with CTA. Include [B-ROLL] and [PAUSE] notes.`,
  },
  {
    id: "landing-page",
    name: "Landing Page",
    icon: "🚀",
    color: "#a78bfa",
    category: "Marketing",
    description: "Full copy for high-converting landing pages",
    fields: [
      { key: "product", label: "Product/Service", type: "text", placeholder: "e.g. AI-powered fitness app" },
      { key: "headline", label: "Main Benefit", type: "text", placeholder: "e.g. Lose 10kg in 90 days without the gym" },
      { key: "audience", label: "Target Audience", type: "text", placeholder: "e.g. Busy professionals aged 30-50" },
      { key: "offer", label: "Offer/Price", type: "text", placeholder: "e.g. Free 14-day trial, no credit card" },
    ],
    systemPrompt: (fields) => `You are a conversion copywriter. Write complete landing page copy for: "${fields.product}". Core benefit: ${fields.headline}. Audience: ${fields.audience}. Offer: ${fields.offer}. Include: hero headline + subheadline, value proposition, 3 key benefits, social proof section, FAQ (5 questions), and strong CTA. Use persuasion principles and clear formatting.`,
  },
];

export const CATEGORIES = [...new Set(TOOLS.map(t => t.category))];
